GLOBAL_ACCEPT_ACCOUNTS = []
GLOBAL_TOTAL_ACCOUNTS = []

GLOBAL_ACCOUNTS_FOR_LEFT = []
GLOBAL_ACCOUNTS_FOR_RIGHT = []
GLOBAL_ACCOUNTS_FOR_UP = []
lasttime = []

GLOBAL_ACCEPT_ACCOUNTS.append(0)
GLOBAL_TOTAL_ACCOUNTS.append(0)
GLOBAL_ACCOUNTS_FOR_RIGHT.append(0)
GLOBAL_ACCOUNTS_FOR_LEFT.append(0)
GLOBAL_ACCOUNTS_FOR_UP.append(0)
lasttime.append(0)


def cleanFace():
    GLOBAL_ACCEPT_ACCOUNTS[0] = 0
    GLOBAL_TOTAL_ACCOUNTS[0] = 0

def cleanHead():
    GLOBAL_ACCOUNTS_FOR_LEFT[0] = 0
    GLOBAL_ACCOUNTS_FOR_RIGHT[0] = 0
    GLOBAL_ACCOUNTS_FOR_UP[0] = 0
